sudo: required

language: generic

services:
  - docker

before_script:
  - cd tests
  - docker-compose up -d
  - docker-compose run --rm node npm run build

script:
  - docker-compose exec node npm test